### ISSUE TITLE
Slow algorithm when printing lines (Chart.line) with color=True 

### ISSUE THREAD

**Issue by carlosplanchon** [carlosplanchon/outfancy#2]
That happens because one character is inserted per "pixel" when color is necessary.

We end with render strings that have +90000 characters, (most of them special characters), which make print() to raise a fuss.

**Comment by guilledk** [comment]
Latest benchmark:

`unitest.py`

- Old code: ⁠⁠⁠93361 chars
- New code: ⁠⁠⁠11822 chars

87.33% less chars
